### ISSUE TITLE
Brew update fails 

### ISSUE THREAD

**Issue by gorkem** [tektoncd/homebrew-tools#2]
I think brew fails because of the branch rename

# Expected Behavior
brew update to succeed

# Actual Behavior
```shell
❯ brew update
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/tektoncd/homebrew-tools failed!
```
# Additional Info

**Comment by chmouel** [comment]
@gorkem we swiched over some time ago to the official homebrew tool :  

https://formulae.brew.sh/formula/tektoncd-cli

can you do a :

```
brew untap tektoncd/tools
```

and install tektoncd-cli from the official repo : 

```brew install tektoncd-cli```

We don't have a easy way to communicate that change except in the release notes which i think was done a couple of releases ago.

**Comment by micxer** [comment]
Well, the README still says:

```
brew tap tektoncd/tools
brew install tektoncd-cli
```

This should be changed as well then.

**Comment by chmouel** [comment]
@micxer oh thanks, i didn't realise we didn't merge the patch..

**Comment by chmouel** [comment]
@micxer Which README tho ? AFAICS the one on master uses the official repo : 

https://github.com/tektoncd/cli#installing-tkn

**Comment by chmouel** [comment]
I have updated the informations on https://github.com/tektoncd/homebrew-tools if that's the one you were looking at.

**Comment by gorkem** [comment]
I did not even notice the switch until the old repo was broken. What is the best practice for such moves?

**Comment by chmouel** [comment]
AFAIK there is no such things in homebrew to communicate a tap deprecation..

**Comment by micxer** [comment]
@chmouel Yeah, thanks. That was the one.

**Comment by chmouel** [comment]
FYI: brew 3.0 should handle the renames transparently https://github.com/Homebrew/brew/pull/10423

**Comment by vincentgerris** [comment]
I had another but related issue:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tektoncd/tools tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/tektoncd/homebrew-tools/Formula/tektoncd-cli.rb:6
```

Tried:
```
brew untap tektoncd/tools
'Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tektoncd/tools tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/tektoncd/homebrew-tools/Formula/tektoncd-cli.rb:6

Error: Refusing to untap tektoncd/tools because it contains the following installed formulae or casks:
tektoncd-cli
```

Had to do:
```
brew remove tektoncd-cli
then
brew untap tektoncd/tools
and finally
brew install tektoncd-cli
```
Then the problem was resolved.

**Comment by chmouel** [comment]
yep, we need to do a new release with the updated goreleaser https://github.com/tektoncd/catalog/commit/03344fec88da34b794e2aac38fef5e949bc2b05c or just let people figuring out they should switch to the official brew repo
