### ISSUE TITLE
"Calling bottle :unneeded is deprecated!" warning

### ISSUE THREAD

**Issue by bobbydennett** [tektoncd/homebrew-tools#5]
# Expected Behavior

Should not receive a `tektoncd/tools` tap-related warning when running `brew` commands such as `brew update`

# Actual Behavior

When running `brew` commands, the following warning is shown:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tektoncd/tools tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/tektoncd/homebrew-tools/Formula/tektoncd-cli.rb:6
```

# Steps to Reproduce the Problem

Run a common `brew` command:
1. `brew update`
2. `brew outdated`
3. `brew upgrade ...`

# Additional Info

Commenting line 6 in the `tektoncd-cli.rb` file fixes the behavior (i.e., removes the warning). https://github.com/Homebrew/discussions/discussions/2311#discussioncomment-1507233 has more details and mentions `bottle :unneeded` is a no-op outside of `Homebrew/core`.

**Comment by AlanGreene** [comment]
This repo is deprecated, the Tekton CLI is available in the official homebrew repo: https://formulae.brew.sh/formula/tektoncd-cli, see https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tektoncd-cli.rb

/close
